// Code generated by "stringer -type=KeyType -linecomment"; DO NOT EDIT.

package digest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MD5-0]
}

const _KeyType_name = "MD5"

var _KeyType_index = [...]uint8{0, 3}

func (i KeyType) String() string {
	if i < 0 || i >= KeyType(len(_KeyType_index)-1) {
		return "KeyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyType_name[_KeyType_index[i]:_KeyType_index[i+1]]
}
