// Code generated by "stringer -type=Err -linecomment"; DO NOT EDIT.

package mq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrTopicFormat-0]
	_ = x[ErrInvalidUrl-1]
	_ = x[ErrNoSuchConsumer-2]
	_ = x[ErrConnectBroken-3]
	_ = x[ErrDeadline-4]
	_ = x[ErrMqType-5]
}

const _Err_name = "pulsar should in format (persistent|non-persistent)://tenant/namespace/topicinvalid mq urlno such consumermq net connection is brokencontext deadline exceedinvalid mq type"

var _Err_index = [...]uint8{0, 76, 90, 106, 133, 156, 171}

func (i Err) String() string {
	if i < 0 || i >= Err(len(_Err_index)-1) {
		return "Err(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Err_name[_Err_index[i]:_Err_index[i+1]]
}
