// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package rds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownType-0]
	_ = x[Mysql-1]
	_ = x[Sqlite-2]
}

const _Type_name = "UnknownTypeMysqlSqlite"

var _Type_index = [...]uint8{0, 11, 16, 22}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
