// Code generated by "stringer -type=ErrCode -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Code1-0]
	_ = x[Code2-1]
	_ = x[Code3-2]
}

const _ErrCode_name = "this is error code1this is error code2this is error code3"

var _ErrCode_index = [...]uint8{0, 19, 38, 57}

func (i ErrCode) String() string {
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
