// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package binding

// Injectors from wire.go:

func injectFooBar() Footer {
	myFooter := provideMyFooter()
	return myFooter
}
