// Code generated by "stringer -type=Mode -linecomment"; DO NOT EDIT.

package aes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ECB-0]
	_ = x[CBC-1]
	_ = x[CFB-2]
	_ = x[CTR-3]
	_ = x[OFB-4]
}

const _Mode_name = "ECBCBCCFBCTROFB"

var _Mode_index = [...]uint8{0, 3, 6, 9, 12, 15}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
