// Code generated by "stringer -type=err -linecomment"; DO NOT EDIT.

package s3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownErrCode-0]
	_ = x[IllegalParams-1]
}

const _Err_name = "UnknownErrCodewrong params"

var _Err_index = [...]uint8{0, 14, 26}

func (i err) String() string {
	if i < 0 || i >= err(len(_Err_index)-1) {
		return "err(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Err_name[_Err_index[i]:_Err_index[i+1]]
}
